name: Gelande/Strasse
favicon: null
layout_spectrum: 0.33638850855641067
typography_spectrum: 0.21400603279471397
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3892304487526417
  lightness: 0.6302687148563564
  saturation: 0.28835963970050216
  rhythmicContrast: 0.5115867822896689
purpose: []
